drop table Moves;

CREATE TABLE Moves (
     id SMALLINT,
     moveName CHAR(20),
     moveType CHAR(10),
     basepower SMALLINT,
     category CHAR(10),
     accuracy SMALLINT,
     PRIMARY KEY(id)
);

INSERT INTO Moves VALUES (1,'Megahorn', 'Bug', 120, 'Physical', 85);
INSERT INTO Moves VALUES (2,'Attack Order', 'Bug', 90, 'Physical', 100);
INSERT INTO Moves VALUES (3,'Bug Buzz', 'Bug', 90, 'Special', 100);
INSERT INTO Moves VALUES (4,'First Impression', 'Bug', 90, 'Physical', 100);
INSERT INTO Moves VALUES (5,'Pollen Puff', 'Bug', 90, 'Special', 100);
INSERT INTO Moves VALUES (6,'Leech Life', 'Bug', 80, 'Physical', 100);
INSERT INTO Moves VALUES (7,'Lunge', 'Bug', 80, 'Physical', 100);
INSERT INTO Moves VALUES (8,'X-Scissor', 'Bug', 80, 'Physical', 100);
INSERT INTO Moves VALUES (9,'Signal Beam', 'Bug', 75, 'Special', 100);
INSERT INTO Moves VALUES (10,'Skitter Smack', 'Bug', 70, 'Physical', 90);
INSERT INTO Moves VALUES (11,'U-turn', 'Bug', 70, 'Physical', 100);
INSERT INTO Moves VALUES (12,'Steamroller', 'Bug', 65, 'Physical', 100);
INSERT INTO Moves VALUES (13,'Bug Bite', 'Bug', 60, 'Physical', 100);
INSERT INTO Moves VALUES (14,'Silver Wind', 'Bug', 60, 'Special', 100);
INSERT INTO Moves VALUES (15,'Fell Stinger', 'Bug', 50, 'Physical', 100);
INSERT INTO Moves VALUES (16,'Struggle Bug', 'Bug', 50, 'Special', 100);
INSERT INTO Moves VALUES (17,'Fury Cutter', 'Bug', 40, 'Physical', 95);
INSERT INTO Moves VALUES (18,'Pin Missile', 'Bug', 25, 'Physical', 95);
INSERT INTO Moves VALUES (19,'Twineedle', 'Bug', 25, 'Physical', 100);
INSERT INTO Moves VALUES (20,'Infestation', 'Bug', 20, 'Special', 100);
INSERT INTO Moves VALUES (21 ,'Defend Order', 'Bug', NULL, 'Status', 0);
INSERT INTO Moves VALUES (22 ,'Heal Order', 'Bug', NULL, 'Status', 0);
INSERT INTO Moves VALUES (23 ,'Powder', 'Bug', NULL, 'Status', 100);
INSERT INTO Moves VALUES (24 ,'Quiver Dance', 'Bug', NULL, 'Status', 0);
INSERT INTO Moves VALUES (25 ,'Rage Powder', 'Bug', NULL, 'Status', 0);
INSERT INTO Moves VALUES (26 ,'Spider Web', 'Bug', NULL, 'Status', 0);
INSERT INTO Moves VALUES (27 ,'Sticky Web', 'Bug', NULL, 'Status', 0);
INSERT INTO Moves VALUES (28 ,'String Shot', 'Bug', NULL, 'Status', 95);
INSERT INTO Moves VALUES (29 ,'Tail Glow', 'Bug', NULL, 'Status', 0);
INSERT INTO Moves VALUES (30,'Hyperspace Fury', 'Dark', 100, 'Physical', 0);
INSERT INTO Moves VALUES (31,'Foul Play', 'Dark', 95, 'Physical', 100);
INSERT INTO Moves VALUES (32,'Fiery Wrath', 'Dark', 90, 'Special', 100);
INSERT INTO Moves VALUES (33,'Darkest Lariat', 'Dark', 85, 'Physical', 100);
INSERT INTO Moves VALUES (34,'Night Daze', 'Dark', 85, 'Special', 95);
INSERT INTO Moves VALUES (35,'Crunch', 'Dark', 80, 'Physical', 100);
INSERT INTO Moves VALUES (36,'Dark Pulse', 'Dark', 80, 'Special', 100);
INSERT INTO Moves VALUES (37,'False Surrender', 'Dark', 80, 'Physical', 0);
INSERT INTO Moves VALUES (38,'Jaw Lock', 'Dark', 80, 'Physical', 100);
INSERT INTO Moves VALUES (39,'Throat Chop', 'Dark', 80, 'Physical', 100);
INSERT INTO Moves VALUES (40,'Wicked Blow', 'Dark', 75, 'Physical', 100);
INSERT INTO Moves VALUES (41,'Lash Out', 'Dark', 75, 'Physical', 100);
INSERT INTO Moves VALUES (42,'Night Slash', 'Dark', 70, 'Physical', 100);
INSERT INTO Moves VALUES (43,'Sucker Punch', 'Dark', 70, 'Physical', 100);
INSERT INTO Moves VALUES (44,'Knock Off', 'Dark', 65, 'Physical', 100);
INSERT INTO Moves VALUES (45,'Assurance', 'Dark', 60, 'Physical', 100);
INSERT INTO Moves VALUES (46,'Bite', 'Dark', 60, 'Physical', 100);
INSERT INTO Moves VALUES (47,'Brutal Swing', 'Dark', 60, 'Physical', 100);
INSERT INTO Moves VALUES (48,'Feint Attack', 'Dark', 60, 'Physical', 0);
INSERT INTO Moves VALUES (49,'Thief', 'Dark', 60, 'Physical', 100);
INSERT INTO Moves VALUES (50,'Snarl', 'Dark', 55, 'Special', 95);
INSERT INTO Moves VALUES (51,'Payback', 'Dark', 50, 'Physical', 100);
INSERT INTO Moves VALUES (52,'Pursuit', 'Dark', 40, 'Physical', 100);
INSERT INTO Moves VALUES (53,'Beat Up', 'Dark', 1, 'Physical', 100);
INSERT INTO Moves VALUES (54,'Fling', 'Dark', 1, 'Physical', 100);
INSERT INTO Moves VALUES (55,'Power Trip', 'Dark', 1, 'Physical', 100);
INSERT INTO Moves VALUES (56,'Punishment', 'Dark', 1, 'Physical', 100);
INSERT INTO Moves VALUES (57 ,'Dark Void', 'Dark', NULL, 'Status', 50);
INSERT INTO Moves VALUES (58 ,'Embargo', 'Dark', NULL, 'Status', 100);
INSERT INTO Moves VALUES (59 ,'Fake Tears', 'Dark', NULL, 'Status', 100);
INSERT INTO Moves VALUES (60 ,'Flatter', 'Dark', NULL, 'Status', 100);
INSERT INTO Moves VALUES (61 ,'Hone Claws', 'Dark', NULL, 'Status', 0);
INSERT INTO Moves VALUES (62 ,'Memento', 'Dark', NULL, 'Status', 100);
INSERT INTO Moves VALUES (63 ,'Nasty Plot', 'Dark', NULL, 'Status', 0);
INSERT INTO Moves VALUES (64 ,'Obstruct', 'Dark', NULL, 'Status', 100);
INSERT INTO Moves VALUES (65 ,'Parting Shot', 'Dark', NULL, 'Status', 100);
INSERT INTO Moves VALUES (66 ,'Quash', 'Dark', NULL, 'Status', 100);
INSERT INTO Moves VALUES (67 ,'Snatch', 'Dark', NULL, 'Status', 0);
INSERT INTO Moves VALUES (68 ,'Switcheroo', 'Dark', NULL, 'Status', 100);
INSERT INTO Moves VALUES (69 ,'Taunt', 'Dark', NULL, 'Status', 100);
INSERT INTO Moves VALUES (70 ,'Topsy-Turvy', 'Dark', NULL, 'Status', 0);
INSERT INTO Moves VALUES (71 ,'Torment', 'Dark', NULL, 'Status', 100);
INSERT INTO Moves VALUES (72,'Eternabeam', 'Dragon', 160, 'Special', 90);
INSERT INTO Moves VALUES (73,'Dragon Energy', 'Dragon', 150, 'Special', 100);
INSERT INTO Moves VALUES (74,'Roar of Time', 'Dragon', 150, 'Special', 90);
INSERT INTO Moves VALUES (75,'Draco Meteor', 'Dragon', 130, 'Special', 90);
INSERT INTO Moves VALUES (76,'Outrage', 'Dragon', 120, 'Physical', 100);
INSERT INTO Moves VALUES (77,'Clanging Scales', 'Dragon', 110, 'Special', 100);
INSERT INTO Moves VALUES (78,'Core Enforcer', 'Dragon', 100, 'Special', 100);
INSERT INTO Moves VALUES (79,'Dragon Rush', 'Dragon', 100, 'Physical', 75);
INSERT INTO Moves VALUES (80,'Dynamax Cannon', 'Dragon', 100, 'Special', 100);
INSERT INTO Moves VALUES (81,'Spacial Rend', 'Dragon', 100, 'Special', 95);
INSERT INTO Moves VALUES (82,'Dragon Hammer', 'Dragon', 90, 'Physical', 100);
INSERT INTO Moves VALUES (83,'Dragon Pulse', 'Dragon', 85, 'Special', 100);
INSERT INTO Moves VALUES (84,'Dragon Claw', 'Dragon', 80, 'Physical', 100);
INSERT INTO Moves VALUES (85,'Breaking Swipe', 'Dragon', 60, 'Physical', 100);
INSERT INTO Moves VALUES (86,'Dragon Breath', 'Dragon', 60, 'Special', 100);
INSERT INTO Moves VALUES (87,'Dragon Tail', 'Dragon', 60, 'Physical', 90);
INSERT INTO Moves VALUES (88,'Dragon Darts', 'Dragon', 50, 'Physical', 100);
INSERT INTO Moves VALUES (89,'Dual Chop', 'Dragon', 40, 'Physical', 90);
INSERT INTO Moves VALUES (90,'Twister', 'Dragon', 40, 'Special', 100);
INSERT INTO Moves VALUES (91,'Scale Shot', 'Dragon', 25, 'Physical', 90);
INSERT INTO Moves VALUES (92,'Dragon Rage', 'Dragon', 1, 'Special', 100);
INSERT INTO Moves VALUES (93 ,'Clangorous Soul', 'Dragon', NULL, 'Status', 100);
INSERT INTO Moves VALUES (94 ,'Dragon Dance', 'Dragon', NULL, 'Status', 0);
INSERT INTO Moves VALUES (95,'Bolt Strike', 'Electric', 130, 'Physical', 85);
INSERT INTO Moves VALUES (96,'Volt Tackle', 'Electric', 120, 'Physical', 100);
INSERT INTO Moves VALUES (97,'Zap Cannon', 'Electric', 120, 'Special', 50);
INSERT INTO Moves VALUES (98,'Aura Wheel', 'Electric', 110, 'Physical', 100);
INSERT INTO Moves VALUES (99,'Thunder', 'Electric', 110, 'Special', 70);
INSERT INTO Moves VALUES (100,'Fusion Bolt', 'Electric', 100, 'Physical', 100);
INSERT INTO Moves VALUES (101,'Plasma Fists', 'Electric', 100, 'Physical', 100);
INSERT INTO Moves VALUES (102,'Thunderbolt', 'Electric', 90, 'Special', 100);
INSERT INTO Moves VALUES (103,'Wild Charge', 'Electric', 90, 'Physical', 100);
INSERT INTO Moves VALUES (104,'Bolt Beak', 'Electric', 85, 'Physical', 100);
INSERT INTO Moves VALUES (105,'Discharge', 'Electric', 80, 'Special', 100);
INSERT INTO Moves VALUES (106,'Overdrive', 'Electric', 80, 'Special', 100);
INSERT INTO Moves VALUES (107,'Thunder Cage', 'Electric', 80, 'Special', 90);
INSERT INTO Moves VALUES (108,'Zing Zap', 'Electric', 80, 'Physical', 100);
INSERT INTO Moves VALUES (109,'Thunder Punch', 'Electric', 75, 'Physical', 100);
INSERT INTO Moves VALUES (110,'Rising Voltage', 'Electric', 70, 'Special', 100);
INSERT INTO Moves VALUES (111,'Volt Switch', 'Electric', 70, 'Special', 100);
INSERT INTO Moves VALUES (112,'Parabolic Charge', 'Electric', 65, 'Special', 100);
INSERT INTO Moves VALUES (113,'Spark', 'Electric', 65, 'Physical', 100);
INSERT INTO Moves VALUES (114,'Thunder Fang', 'Electric', 65, 'Physical', 95);
INSERT INTO Moves VALUES (115,'Shock Wave', 'Electric', 60, 'Special', 0);
INSERT INTO Moves VALUES (116,'Electroweb', 'Electric', 55, 'Special', 95);
INSERT INTO Moves VALUES (117,'Charge Beam', 'Electric', 50, 'Special', 90);
INSERT INTO Moves VALUES (118,'Thunder Shock', 'Electric', 40, 'Special', 100);
INSERT INTO Moves VALUES (119,'Nuzzle', 'Electric', 20, 'Physical', 100);
INSERT INTO Moves VALUES (120,'Electro Ball', 'Electric', 1, 'Special', 100);
INSERT INTO Moves VALUES (121 ,'Charge', 'Electric', NULL, 'Status', 0);
INSERT INTO Moves VALUES (122 ,'Eerie Impulse', 'Electric', NULL, 'Status', 100);
INSERT INTO Moves VALUES (123 ,'Electric Terrain', 'Electric', NULL, 'Status', 0);
INSERT INTO Moves VALUES (124 ,'Electrify', 'Electric', NULL, 'Status', 0);
INSERT INTO Moves VALUES (125 ,'Ion Deluge', 'Electric', NULL, 'Status', 0);
INSERT INTO Moves VALUES (126 ,'Magnet Rise', 'Electric', NULL, 'Status', 0);
INSERT INTO Moves VALUES (127 ,'Magnetic Flux', 'Electric', NULL, 'Status', 0);
INSERT INTO Moves VALUES (128 ,'Thunder Wave', 'Electric', NULL, 'Status', 90);
INSERT INTO Moves VALUES (129,'Light of Ruin', 'Fairy', 140, 'Special', 90);
INSERT INTO Moves VALUES (130,'Fleur Cannon', 'Fairy', 130, 'Special', 90);
INSERT INTO Moves VALUES (131,'Misty Explosion', 'Fairy', 100, 'Special', 100);
INSERT INTO Moves VALUES (132,'Moonblast', 'Fairy', 95, 'Special', 100);
INSERT INTO Moves VALUES (133,'Play Rough', 'Fairy', 90, 'Physical', 90);
INSERT INTO Moves VALUES (134,'Strange Steam', 'Fairy', 90, 'Special', 95);
INSERT INTO Moves VALUES (135,'Dazzling Gleam', 'Fairy', 80, 'Special', 100);
INSERT INTO Moves VALUES (136,'Spirit Break', 'Fairy', 75, 'Physical', 100);
INSERT INTO Moves VALUES (137,'Draining Kiss', 'Fairy', 50, 'Special', 100);
INSERT INTO Moves VALUES (138,'Disarming Voice', 'Fairy', 40, 'Special', 0);
INSERT INTO Moves VALUES (139,'Fairy Wind', 'Fairy', 40, 'Special', 100);
INSERT INTO Moves VALUES (140,'Natures Madness', 'Fairy', 1, 'Special', 90);
INSERT INTO Moves VALUES (141 ,'Aromatic Mist', 'Fairy', NULL, 'Status', 0);
INSERT INTO Moves VALUES (142 ,'Baby-Doll Eyes', 'Fairy', NULL, 'Status', 100);
INSERT INTO Moves VALUES (143 ,'Charm', 'Fairy', NULL, 'Status', 100);
INSERT INTO Moves VALUES (144 ,'Crafty Shield', 'Fairy', NULL, 'Status', 0);
INSERT INTO Moves VALUES (145 ,'Decorate', 'Fairy', NULL, 'Status', 0);
INSERT INTO Moves VALUES (146 ,'Fairy Lock', 'Fairy', NULL, 'Status', 0);
INSERT INTO Moves VALUES (147 ,'Floral Healing', 'Fairy', NULL, 'Status', 0);
INSERT INTO Moves VALUES (148 ,'Flower Shield', 'Fairy', NULL, 'Status', 0);
INSERT INTO Moves VALUES (149 ,'Geomancy', 'Fairy', NULL, 'Status', 0);
INSERT INTO Moves VALUES (150 ,'Misty Terrain', 'Fairy', NULL, 'Status', 0);
INSERT INTO Moves VALUES (151 ,'Moonlight', 'Fairy', NULL, 'Status', 0);
INSERT INTO Moves VALUES (152 ,'Sweet Kiss', 'Fairy', NULL, 'Status', 75);
INSERT INTO Moves VALUES (153,'Focus Punch', 'Fighting', 150, 'Physical', 100);
INSERT INTO Moves VALUES (154,'Meteor Assault', 'Fighting', 150, 'Physical', 100);
INSERT INTO Moves VALUES (155,'High Jump Kick', 'Fighting', 130, 'Physical', 90);
INSERT INTO Moves VALUES (156,'Close Combat', 'Fighting', 120, 'Physical', 100);
INSERT INTO Moves VALUES (157,'Focus Blast', 'Fighting', 120, 'Special', 70);
INSERT INTO Moves VALUES (158,'Superpower', 'Fighting', 120, 'Physical', 100);
INSERT INTO Moves VALUES (159,'Cross Chop', 'Fighting', 100, 'Physical', 80);
INSERT INTO Moves VALUES (160,'Dynamic Punch', 'Fighting', 100, 'Physical', 50);
INSERT INTO Moves VALUES (161,'Flying Press', 'Fighting', 100, 'Physical', 95);
INSERT INTO Moves VALUES (162,'Hammer Arm', 'Fighting', 100, 'Physical', 90);
INSERT INTO Moves VALUES (163,'Jump Kick', 'Fighting', 100, 'Physical', 95);
INSERT INTO Moves VALUES (164,'Sacred Sword', 'Fighting', 90, 'Physical', 100);
INSERT INTO Moves VALUES (165,'Thunderous Kick', 'Fighting', 90, 'Physical', 100);
INSERT INTO Moves VALUES (166,'Secret Sword', 'Fighting', 85, 'Special', 100);
INSERT INTO Moves VALUES (167,'Sky Uppercut', 'Fighting', 85, 'Physical', 90);
INSERT INTO Moves VALUES (168,'Aura Sphere', 'Fighting', 80, 'Special', 0);
INSERT INTO Moves VALUES (169,'Body Press', 'Fighting', 80, 'Physical', 100);
INSERT INTO Moves VALUES (170,'Submission', 'Fighting', 80, 'Physical', 80);
INSERT INTO Moves VALUES (171,'Brick Break', 'Fighting', 75, 'Physical', 100);
INSERT INTO Moves VALUES (172,'Drain Punch', 'Fighting', 75, 'Physical', 100);
INSERT INTO Moves VALUES (173,'Vital Throw', 'Fighting', 70, 'Physical', 0);
INSERT INTO Moves VALUES (174,'Wake-Up Slap', 'Fighting', 70, 'Physical', 100);
INSERT INTO Moves VALUES (175,'Low Sweep', 'Fighting', 65, 'Physical', 100);
INSERT INTO Moves VALUES (176,'Circle Throw', 'Fighting', 60, 'Physical', 90);
INSERT INTO Moves VALUES (177,'Force Palm', 'Fighting', 60, 'Physical', 100);
INSERT INTO Moves VALUES (178,'Revenge', 'Fighting', 60, 'Physical', 100);
INSERT INTO Moves VALUES (179,'Rolling Kick', 'Fighting', 60, 'Physical', 85);
INSERT INTO Moves VALUES (180,'Storm Throw', 'Fighting', 60, 'Physical', 100);
INSERT INTO Moves VALUES (181,'Karate Chop', 'Fighting', 50, 'Physical', 100);
INSERT INTO Moves VALUES (182,'Mach Punch', 'Fighting', 40, 'Physical', 100);
INSERT INTO Moves VALUES (183,'Power-Up Punch', 'Fighting', 40, 'Physical', 100);
INSERT INTO Moves VALUES (184,'Rock Smash', 'Fighting', 40, 'Physical', 100);
INSERT INTO Moves VALUES (185,'Vacuum Wave', 'Fighting', 40, 'Special', 100);
INSERT INTO Moves VALUES (186,'Double Kick', 'Fighting', 30, 'Physical', 100);
INSERT INTO Moves VALUES (187,'Arm Thrust', 'Fighting', 15, 'Physical', 100);
INSERT INTO Moves VALUES (188,'Triple Kick', 'Fighting', 10, 'Physical', 90);
INSERT INTO Moves VALUES (189,'Counter', 'Fighting', 1, 'Physical', 100);
INSERT INTO Moves VALUES (190,'Final Gambit', 'Fighting', 1, 'Special', 100);
INSERT INTO Moves VALUES (191,'Low Kick', 'Fighting', 1, 'Physical', 100);
INSERT INTO Moves VALUES (192,'Reversal', 'Fighting', 1, 'Physical', 100);
INSERT INTO Moves VALUES (193,'Seismic Toss', 'Fighting', 1, 'Physical', 100);
INSERT INTO Moves VALUES (194 ,'Bulk Up', 'Fighting', NULL, 'Status', 0);
INSERT INTO Moves VALUES (195 ,'Coaching', 'Fighting', NULL, 'Status', 0);
INSERT INTO Moves VALUES (196 ,'Detect', 'Fighting', NULL, 'Status', 0);
INSERT INTO Moves VALUES (197 ,'Mat Block', 'Fighting', NULL, 'Status', 0);
INSERT INTO Moves VALUES (198 ,'No Retreat', 'Fighting', NULL, 'Status', 0);
INSERT INTO Moves VALUES (199 ,'Octolock', 'Fighting', NULL, 'Status', 100);
INSERT INTO Moves VALUES (200 ,'Quick Guard', 'Fighting', NULL, 'Status', 0);
INSERT INTO Moves VALUES (201,'V-create', 'Fire', 180, 'Physical', 95);
INSERT INTO Moves VALUES (202,'Blast Burn', 'Fire', 150, 'Special', 90);
INSERT INTO Moves VALUES (203,'Eruption', 'Fire', 150, 'Special', 100);
INSERT INTO Moves VALUES (204,'Mind Blown', 'Fire', 150, 'Special', 100);
INSERT INTO Moves VALUES (205,'Shell Trap', 'Fire', 150, 'Special', 100);
INSERT INTO Moves VALUES (206,'Blue Flare', 'Fire', 130, 'Special', 85);
INSERT INTO Moves VALUES (207,'Burn Up', 'Fire', 130, 'Special', 100);
INSERT INTO Moves VALUES (208,'Overheat', 'Fire', 130, 'Special', 90);
INSERT INTO Moves VALUES (209,'Flare Blitz', 'Fire', 120, 'Physical', 100);
INSERT INTO Moves VALUES (210,'Pyro Ball', 'Fire', 120, 'Physical', 90);
INSERT INTO Moves VALUES (211,'Fire Blast', 'Fire', 110, 'Special', 85);
INSERT INTO Moves VALUES (212,'Fusion Flare', 'Fire', 100, 'Special', 100);
INSERT INTO Moves VALUES (213,'Inferno', 'Fire', 100, 'Special', 50);
INSERT INTO Moves VALUES (214,'Magma Storm', 'Fire', 100, 'Special', 75);
INSERT INTO Moves VALUES (215,'Sacred Fire', 'Fire', 100, 'Physical', 95);
INSERT INTO Moves VALUES (216,'Searing Shot', 'Fire', 100, 'Special', 100);
INSERT INTO Moves VALUES (217,'Heat Wave', 'Fire', 95, 'Special', 90);
INSERT INTO Moves VALUES (218,'Flamethrower', 'Fire', 90, 'Special', 100);
INSERT INTO Moves VALUES (219,'Blaze Kick', 'Fire', 85, 'Physical', 90);
INSERT INTO Moves VALUES (220,'Fiery Dance', 'Fire', 80, 'Special', 100);
INSERT INTO Moves VALUES (221,'Fire Lash', 'Fire', 80, 'Physical', 100);
INSERT INTO Moves VALUES (222,'Fire Pledge', 'Fire', 80, 'Special', 100);
INSERT INTO Moves VALUES (223,'Lava Plume', 'Fire', 80, 'Special', 100);
INSERT INTO Moves VALUES (224,'Fire Punch', 'Fire', 75, 'Physical', 100);
INSERT INTO Moves VALUES (225,'Mystical Fire', 'Fire', 75, 'Special', 100);
INSERT INTO Moves VALUES (226,'Burning Jealousy', 'Fire', 70, 'Special', 100);
INSERT INTO Moves VALUES (227,'Flame Burst', 'Fire', 70, 'Special', 100);
INSERT INTO Moves VALUES (228,'Fire Fang', 'Fire', 65, 'Physical', 95);
INSERT INTO Moves VALUES (229,'Flame Wheel', 'Fire', 60, 'Physical', 100);
INSERT INTO Moves VALUES (230,'Incinerate', 'Fire', 60, 'Special', 100);
INSERT INTO Moves VALUES (231,'Flame Charge', 'Fire', 50, 'Physical', 100);
INSERT INTO Moves VALUES (232,'Ember', 'Fire', 40, 'Special', 100);
INSERT INTO Moves VALUES (233,'Fire Spin', 'Fire', 35, 'Special', 85);
INSERT INTO Moves VALUES (234,'Heat Crash', 'Fire', 1, 'Physical', 100);
INSERT INTO Moves VALUES (235 ,'Sunny Day', 'Fire', NULL, 'Status', 0);
INSERT INTO Moves VALUES (236 ,'Will-O-Wisp', 'Fire', NULL, 'Status', 85);
INSERT INTO Moves VALUES (237,'Sky Attack', 'Flying', 140, 'Physical', 90);
INSERT INTO Moves VALUES (238,'Brave Bird', 'Flying', 120, 'Physical', 100);
INSERT INTO Moves VALUES (239,'Dragon Ascent', 'Flying', 120, 'Physical', 100);
INSERT INTO Moves VALUES (240,'Hurricane', 'Flying', 110, 'Special', 70);
INSERT INTO Moves VALUES (241,'Aeroblast', 'Flying', 100, 'Special', 95);
INSERT INTO Moves VALUES (242,'Beak Blast', 'Flying', 100, 'Physical', 100);
INSERT INTO Moves VALUES (243,'Fly', 'Flying', 90, 'Physical', 95);
INSERT INTO Moves VALUES (244,'Bounce', 'Flying', 85, 'Physical', 85);
INSERT INTO Moves VALUES (245,'Drill Peck', 'Flying', 80, 'Physical', 100);
INSERT INTO Moves VALUES (246,'Oblivion Wing', 'Flying', 80, 'Special', 100);
INSERT INTO Moves VALUES (247,'Air Slash', 'Flying', 75, 'Special', 95);
INSERT INTO Moves VALUES (248,'Chatter', 'Flying', 65, 'Special', 100);
INSERT INTO Moves VALUES (249,'Aerial Ace', 'Flying', 60, 'Physical', 0);
INSERT INTO Moves VALUES (250,'Air Cutter', 'Flying', 60, 'Special', 95);
INSERT INTO Moves VALUES (251,'Pluck', 'Flying', 60, 'Physical', 100);
INSERT INTO Moves VALUES (252,'Sky Drop', 'Flying', 60, 'Physical', 100);
INSERT INTO Moves VALUES (253,'Wing Attack', 'Flying', 60, 'Physical', 100);
INSERT INTO Moves VALUES (254,'Acrobatics', 'Flying', 55, 'Physical', 100);
INSERT INTO Moves VALUES (255,'Dual Wingbeat', 'Flying', 40, 'Physical', 90);
INSERT INTO Moves VALUES (256,'Gust', 'Flying', 40, 'Special', 100);
INSERT INTO Moves VALUES (257,'Peck', 'Flying', 35, 'Physical', 100);
INSERT INTO Moves VALUES (258 ,'Defog', 'Flying', NULL, 'Status', 0);
INSERT INTO Moves VALUES (259 ,'Feather Dance', 'Flying', NULL, 'Status', 100);
INSERT INTO Moves VALUES (260 ,'Mirror Move', 'Flying', NULL, 'Status', 0);
INSERT INTO Moves VALUES (261 ,'Roost', 'Flying', NULL, 'Status', 0);
INSERT INTO Moves VALUES (262 ,'Tailwind', 'Flying', NULL, 'Status', 0);
INSERT INTO Moves VALUES (263,'Astral Barrage', 'Ghost', 120, 'Special', 100);
INSERT INTO Moves VALUES (264,'Shadow Force', 'Ghost', 120, 'Physical', 100);
INSERT INTO Moves VALUES (265,'Poltergeist', 'Ghost', 110, 'Physical', 90);
INSERT INTO Moves VALUES (266,'Moongeist Beam', 'Ghost', 100, 'Special', 100);
INSERT INTO Moves VALUES (267,'Phantom Force', 'Ghost', 90, 'Physical', 100);
INSERT INTO Moves VALUES (268,'Spectral Thief', 'Ghost', 90, 'Physical', 100);
INSERT INTO Moves VALUES (269,'Shadow Bone', 'Ghost', 85, 'Physical', 100);
INSERT INTO Moves VALUES (270,'Shadow Ball', 'Ghost', 80, 'Special', 100);
INSERT INTO Moves VALUES (271,'Spirit Shackle', 'Ghost', 80, 'Physical', 100);
INSERT INTO Moves VALUES (272,'Shadow Claw', 'Ghost', 70, 'Physical', 100);
INSERT INTO Moves VALUES (273,'Hex', 'Ghost', 65, 'Special', 100);
INSERT INTO Moves VALUES (274,'Ominous Wind', 'Ghost', 60, 'Special', 100);
INSERT INTO Moves VALUES (275,'Shadow Punch', 'Ghost', 60, 'Physical', 0);
INSERT INTO Moves VALUES (276,'Shadow Sneak', 'Ghost', 40, 'Physical', 100);
INSERT INTO Moves VALUES (277,'Astonish', 'Ghost', 30, 'Physical', 100);
INSERT INTO Moves VALUES (278,'Lick', 'Ghost', 30, 'Physical', 100);
INSERT INTO Moves VALUES (279,'Night Shade', 'Ghost', 1, 'Special', 100);
INSERT INTO Moves VALUES (280 ,'Confuse Ray', 'Ghost', NULL, 'Status', 100);
INSERT INTO Moves VALUES (281 ,'Curse', 'Ghost', NULL, 'Status', 0);
INSERT INTO Moves VALUES (282 ,'Destiny Bond', 'Ghost', NULL, 'Status', 0);
INSERT INTO Moves VALUES (283 ,'Grudge', 'Ghost', NULL, 'Status', 0);
INSERT INTO Moves VALUES (284 ,'Nightmare', 'Ghost', NULL, 'Status', 100);
INSERT INTO Moves VALUES (285 ,'Spite', 'Ghost', NULL, 'Status', 100);
INSERT INTO Moves VALUES (286 ,'Trick-or-Treat', 'Ghost', NULL, 'Status', 100);
INSERT INTO Moves VALUES (287,'Frenzy Plant', 'Grass', 150, 'Special', 90);
INSERT INTO Moves VALUES (288,'Leaf Storm', 'Grass', 130, 'Special', 90);
INSERT INTO Moves VALUES (289,'Solar Blade', 'Grass', 125, 'Physical', 100);
INSERT INTO Moves VALUES (290,'Petal Dance', 'Grass', 120, 'Special', 100);
INSERT INTO Moves VALUES (291,'Power Whip', 'Grass', 120, 'Physical', 85);
INSERT INTO Moves VALUES (292,'Seed Flare', 'Grass', 120, 'Special', 85);
INSERT INTO Moves VALUES (293,'Solar Beam', 'Grass', 120, 'Special', 100);
INSERT INTO Moves VALUES (294,'Wood Hammer', 'Grass', 120, 'Physical', 100);
INSERT INTO Moves VALUES (295,'Energy Ball', 'Grass', 90, 'Special', 100);
INSERT INTO Moves VALUES (296,'Leaf Blade', 'Grass', 90, 'Physical', 100);
INSERT INTO Moves VALUES (297,'Petal Blizzard', 'Grass', 90, 'Physical', 100);
INSERT INTO Moves VALUES (298,'Apple Acid', 'Grass', 80, 'Special', 100);
INSERT INTO Moves VALUES (299,'Drum Beating', 'Grass', 80, 'Physical', 100);
INSERT INTO Moves VALUES (300,'Grass Pledge', 'Grass', 80, 'Special', 100);
INSERT INTO Moves VALUES (301,'Grav Apple', 'Grass', 80, 'Physical', 100);
INSERT INTO Moves VALUES (302,'Seed Bomb', 'Grass', 80, 'Physical', 100);
INSERT INTO Moves VALUES (303,'Giga Drain', 'Grass', 75, 'Special', 100);
INSERT INTO Moves VALUES (304,'Horn Leech', 'Grass', 75, 'Physical', 100);
INSERT INTO Moves VALUES (305,'Grassy Glide', 'Grass', 60, 'Physical', 100);
INSERT INTO Moves VALUES (306,'Trop Kick', 'Grass', 70, 'Physical', 100);
INSERT INTO Moves VALUES (307,'Leaf Tornado', 'Grass', 65, 'Special', 90);
INSERT INTO Moves VALUES (308,'Magical Leaf', 'Grass', 60, 'Special', 0);
INSERT INTO Moves VALUES (309,'Needle Arm', 'Grass', 60, 'Physical', 100);
INSERT INTO Moves VALUES (310,'Razor Leaf', 'Grass', 55, 'Physical', 95);
INSERT INTO Moves VALUES (311,'Vine Whip', 'Grass', 45, 'Physical', 100);
INSERT INTO Moves VALUES (312,'Branch Poke', 'Grass', 40, 'Physical', 100);
INSERT INTO Moves VALUES (313,'Leafage', 'Grass', 40, 'Physical', 100);
INSERT INTO Moves VALUES (314,'Mega Drain', 'Grass', 40, 'Special', 100);
INSERT INTO Moves VALUES (315,'Snap Trap', 'Grass', 35, 'Physical', 100);
INSERT INTO Moves VALUES (316,'Bullet Seed', 'Grass', 25, 'Physical', 100);
INSERT INTO Moves VALUES (317,'Absorb', 'Grass', 20, 'Special', 100);
INSERT INTO Moves VALUES (318,'Grass Knot', 'Grass', 1, 'Special', 100);
INSERT INTO Moves VALUES (319 ,'Aromatherapy', 'Grass', NULL, 'Status', 0);
INSERT INTO Moves VALUES (320 ,'Cotton Guard', 'Grass', NULL, 'Status', 0);
INSERT INTO Moves VALUES (321 ,'Cotton Spore', 'Grass', NULL, 'Status', 100);
INSERT INTO Moves VALUES (322 ,'Forests Curse', 'Grass', NULL, 'Status', 100);
INSERT INTO Moves VALUES (323 ,'Grass Whistle', 'Grass', NULL, 'Status', 55);
INSERT INTO Moves VALUES (324 ,'Grassy Terrain', 'Grass', NULL, 'Status', 0);
INSERT INTO Moves VALUES (325 ,'Ingrain', 'Grass', NULL, 'Status', 0);
INSERT INTO Moves VALUES (326 ,'Jungle Healing', 'Grass', NULL, 'Status', 0);
INSERT INTO Moves VALUES (327 ,'Leech Seed', 'Grass', NULL, 'Status', 90);
INSERT INTO Moves VALUES (328 ,'Sleep Powder', 'Grass', NULL, 'Status', 75);
INSERT INTO Moves VALUES (329 ,'Spiky Shield', 'Grass', NULL, 'Status', 0);
INSERT INTO Moves VALUES (330 ,'Spore', 'Grass', NULL, 'Status', 100);
INSERT INTO Moves VALUES (331 ,'Strength Sap', 'Grass', NULL, 'Status', 100);
INSERT INTO Moves VALUES (332 ,'Stun Spore', 'Grass', NULL, 'Status', 75);
INSERT INTO Moves VALUES (333 ,'Synthesis', 'Grass', NULL, 'Status', 0);
INSERT INTO Moves VALUES (334 ,'Worry Seed', 'Grass', NULL, 'Status', 100);
INSERT INTO Moves VALUES (335,'Precipice Blades', 'Ground', 120, 'Physical', 85);
INSERT INTO Moves VALUES (336,'Earthquake', 'Ground', 100, 'Physical', 100);
INSERT INTO Moves VALUES (337,'High Horsepower', 'Ground', 95, 'Physical', 95);
INSERT INTO Moves VALUES (338,'Earth Power, 'Ground', 90, 'Special', 100);
INSERT INTO Moves VALUES (339,'Land's Wrath', 'Ground', 90, 'Physical', 100);
INSERT INTO Moves VALUES (340,'Thousand Arrows', 'Ground', 90, 'Physical', 100);
INSERT INTO Moves VALUES (341,'Thousand Waves', 'Ground', 90, 'Physical', 100);
INSERT INTO Moves VALUES (342,'Dig', 'Ground', 80, 'Physical', 100);
INSERT INTO Moves VALUES (343,'Drill Run', 'Ground', 80, 'Physical', 95);
INSERT INTO Moves VALUES (344,'Stomping Tantrum', 'Ground', 75, 'Physical', 100);
INSERT INTO Moves VALUES (345,'Scorching Sands', 'Ground', 70, 'Special', 100);
INSERT INTO Moves VALUES (346,'Bone Club', 'Ground', 65, 'Physical', 85);
INSERT INTO Moves VALUES (347,'Mud Bomb', 'Ground', 65, 'Special', 85);
INSERT INTO Moves VALUES (348,'Bulldoze', 'Ground', 60, 'Physical', 100);
INSERT INTO Moves VALUES (349,'Mud Shot', 'Ground', 55, 'Special', 95);
INSERT INTO Moves VALUES (350,'Bonemerang', 'Ground', 50, 'Physical', 90);
INSERT INTO Moves VALUES (351,'Sand Tomb', 'Ground', 35, 'Physical', 85);
INSERT INTO Moves VALUES (352,'Bone Rush', 'Ground', 25, 'Physical', 90);
INSERT INTO Moves VALUES (353,'Mud-Slap', 'Ground', 20, 'Special', 100);
INSERT INTO Moves VALUES (354,'Fissure', 'Ground', 1, 'Physical', 30);
INSERT INTO Moves VALUES (355,'Magnitude', 'Ground', 1, 'Physical', 100);
INSERT INTO Moves VALUES (356 ,'Mud Sport', 'Ground', NULL, 'Status', 0);
INSERT INTO Moves VALUES (357 ,'Rototiller', 'Ground', NULL, 'Status', 0);
INSERT INTO Moves VALUES (358 ,'Sand Attack', 'Ground', NULL, 'Status', 100);
INSERT INTO Moves VALUES (359 ,'Shore Up', 'Ground', NULL, 'Status', 0);
INSERT INTO Moves VALUES (360 ,'Spikes', 'Ground', NULL, 'Status', 0);
INSERT INTO Moves VALUES (361,'Freeze Shock', 'Ice', 140, 'Physical', 90);
INSERT INTO Moves VALUES (362,'Ice Burn', 'Ice', 140, 'Special', 90);
INSERT INTO Moves VALUES (363,'Glacial Lance', 'Ice', 120, 'Physical', 100);
INSERT INTO Moves VALUES (364,'Blizzard', 'Ice', 110, 'Special', 70);
INSERT INTO Moves VALUES (365,'Ice Hammer', 'Ice', 100, 'Physical', 90);
INSERT INTO Moves VALUES (366,'Ice Beam', 'Ice', 90, 'Special', 100);
INSERT INTO Moves VALUES (367,'Icicle Crash', 'Ice', 85, 'Physical', 90);
INSERT INTO Moves VALUES (368,'Ice Punch', 'Ice', 75, 'Physical', 100);
INSERT INTO Moves VALUES (369,'Freeze-Dry', 'Ice', 70, 'Special', 100);
INSERT INTO Moves VALUES (370,'Aurora Beam', 'Ice', 65, 'Special', 100);
INSERT INTO Moves VALUES (371,'Glaciate', 'Ice', 65, 'Special', 95);
INSERT INTO Moves VALUES (372,'Ice Fang', 'Ice', 65, 'Physical', 95);
INSERT INTO Moves VALUES (373,'Avalanche', 'Ice', 60, 'Physical', 100);
INSERT INTO Moves VALUES (374,'Frost Breath', 'Ice', 60, 'Special', 90);
INSERT INTO Moves VALUES (375,'Icy Wind', 'Ice', 55, 'Special', 95);
INSERT INTO Moves VALUES (376,'Ice Shard', 'Ice', 40, 'Physical', 100);
INSERT INTO Moves VALUES (377,'Powder Snow', 'Ice', 40, 'Special', 100);
INSERT INTO Moves VALUES (378,'Ice Ball', 'Ice', 30, 'Physical', 90);
INSERT INTO Moves VALUES (379,'Icicle Spear', 'Ice', 25, 'Physical', 100);
INSERT INTO Moves VALUES (380,'Triple Axel', 'Ice', 20, 'Physical', 90);
INSERT INTO Moves VALUES (381,'Sheer Cold', 'Ice', 1, 'Special', 30);
INSERT INTO Moves VALUES (382 ,'Aurora Veil', 'Ice', NULL, 'Status', 0);
INSERT INTO Moves VALUES (383 ,'Hail', 'Ice', NULL, 'Status', 0);
INSERT INTO Moves VALUES (384 ,'Haze', 'Ice', NULL, 'Status', 0);
INSERT INTO Moves VALUES (385 ,'Mist', 'Ice', NULL, 'Status', 0);
INSERT INTO Moves VALUES (386,'Explosion', 'Normal', 250, 'Physical', 100);
INSERT INTO Moves VALUES (387,'Self-Destruct', 'Normal', 200, 'Physical', 100);
INSERT INTO Moves VALUES (388,'Giga Impact', 'Normal', 150, 'Physical', 90);
INSERT INTO Moves VALUES (389,'Hyper Beam', 'Normal', 150, 'Special', 90);
INSERT INTO Moves VALUES (390,'Boomburst', 'Normal', 140, 'Special', 100);
INSERT INTO Moves VALUES (391,'Last Resort', 'Normal', 140, 'Physical', 100);
INSERT INTO Moves VALUES (392,'Skull Bash', 'Normal', 130, 'Physical', 100);
INSERT INTO Moves VALUES (393,'Double-Edge', 'Normal', 120, 'Physical', 100);
INSERT INTO Moves VALUES (394,'Head Charge', 'Normal', 120, 'Physical', 100);
INSERT INTO Moves VALUES (395,'Mega Kick', 'Normal', 120, 'Physical', 75);
INSERT INTO Moves VALUES (396,'Multi-Attack', 'Normal', 120, 'Physical', 100);
INSERT INTO Moves VALUES (397,'Techno Blast', 'Normal', 120, 'Special', 100);
INSERT INTO Moves VALUES (398,'Thrash', 'Normal', 120, 'Physical', 100);
INSERT INTO Moves VALUES (399,'Egg Bomb', 'Normal', 100, 'Physical', 75);
INSERT INTO Moves VALUES (400,'Judgment', 'Normal', 100, 'Special', 100);
INSERT INTO Moves VALUES (401,'Hyper Voice', 'Normal', 90, 'Special', 100);
INSERT INTO Moves VALUES (402,'Revelation Dance', 'Normal', 90, 'Special', 100);
INSERT INTO Moves VALUES (403,'Rock Climb', 'Normal', 90, 'Physical', 85);
INSERT INTO Moves VALUES (404,'Take Down', 'Normal', 90, 'Physical', 85);
INSERT INTO Moves VALUES (405,'Uproar', 'Normal', 90, 'Special', 100);
INSERT INTO Moves VALUES (406,'Body Slam', 'Normal', 85, 'Physical', 100);
INSERT INTO Moves VALUES (407,'Extreme Speed', 'Normal', 80, 'Physical', 100);
INSERT INTO Moves VALUES (408,'Hyper Fang', 'Normal', 80, 'Physical', 90);
INSERT INTO Moves VALUES (409,'Mega Punch', 'Normal', 80, 'Physical', 85);
INSERT INTO Moves VALUES (410,'Razor Wind', 'Normal', 80, 'Special', 100);
INSERT INTO Moves VALUES (411,'Slam', 'Normal', 80, 'Physical', 75);
INSERT INTO Moves VALUES (412,'Strength', 'Normal', 80, 'Physical', 100);
INSERT INTO Moves VALUES (413,'Tri Attack', 'Normal', 80, 'Special', 100);
INSERT INTO Moves VALUES (414,'Crush Claw', 'Normal', 75, 'Physical', 95);
INSERT INTO Moves VALUES (415,'Relic Song', 'Normal', 75, 'Special', 100);
INSERT INTO Moves VALUES (416,'Chip Away', 'Normal', 70, 'Physical', 100);
INSERT INTO Moves VALUES (417,'Dizzy Punch', 'Normal', 70, 'Physical', 100);
INSERT INTO Moves VALUES (418,'Facade', 'Normal', 70, 'Physical', 100);
INSERT INTO Moves VALUES (419,'Headbutt', 'Normal', 70, 'Physical', 100);
INSERT INTO Moves VALUES (420,'Retaliate', 'Normal', 70, 'Physical', 100);
INSERT INTO Moves VALUES (421,'Secret Power', 'Normal', 70, 'Physical', 100);
INSERT INTO Moves VALUES (422,'Slash', 'Normal', 70, 'Physical', 100);
INSERT INTO Moves VALUES (423,'Smelling Salts', 'Normal', 70, 'Physical', 100);
INSERT INTO Moves VALUES (424,'Horn Attack', 'Normal', 65, 'Physical', 100);
INSERT INTO Moves VALUES (425,'Stomp', 'Normal', 65, 'Physical', 100);
INSERT INTO Moves VALUES (426,'Covet', 'Normal', 60, 'Physical', 100);
INSERT INTO Moves VALUES (427,'Hidden Power', 'Normal', 60, 'Special', 100);
INSERT INTO Moves VALUES (428,'Round', 'Normal', 60, 'Special', 100);
INSERT INTO Moves VALUES (429,'Swift', 'Normal', 60, 'Special', 0);
INSERT INTO Moves VALUES (430,'Vise Grip', 'Normal', 55, 'Physical', 100);
INSERT INTO Moves VALUES (431,'Cut', 'Normal', 50, 'Physical', 95);
INSERT INTO Moves VALUES (432,'Rapid Spin', 'Normal', 50, 'Physical', 100);
INSERT INTO Moves VALUES (433,'Snore', 'Normal', 50, 'Special', 100);
INSERT INTO Moves VALUES (434,'Struggle', 'Normal', 50, 'Physical', 0);
INSERT INTO Moves VALUES (435,'Terrain Pulse', 'Normal', 50, 'Special', 100);
INSERT INTO Moves VALUES (436,'Weather Ball', 'Normal', 50, 'Special', 100);
INSERT INTO Moves VALUES (437,'Echoed Voice', 'Normal', 40, 'Special', 100);
INSERT INTO Moves VALUES (438,'Fake Out', 'Normal', 40, 'Physical', 100);
INSERT INTO Moves VALUES (439,'False Swipe', 'Normal', 40, 'Physical', 100);
INSERT INTO Moves VALUES (440,'Hold Back', 'Normal', 40, 'Physical', 100);
INSERT INTO Moves VALUES (441,'Pay Day', 'Normal', 40, 'Physical', 100);
INSERT INTO Moves VALUES (442,'Pound', 'Normal', 40, 'Physical', 100);
INSERT INTO Moves VALUES (443,'Quick Attack', 'Normal', 40, 'Physical', 100);
INSERT INTO Moves VALUES (444,'Scratch', 'Normal', 40, 'Physical', 100);
INSERT INTO Moves VALUES (445,'Tackle', 'Normal', 40, 'Physical', 100);
INSERT INTO Moves VALUES (446,'Double Hit', 'Normal', 35, 'Physical', 90);
INSERT INTO Moves VALUES (447,'Feint', 'Normal', 30, 'Physical', 100);
INSERT INTO Moves VALUES (448,'Tail Slap', 'Normal', 25, 'Physical', 85);
INSERT INTO Moves VALUES (449,'Rage', 'Normal', 20, 'Physical', 100);
INSERT INTO Moves VALUES (450,'Spike Cannon', 'Normal', 20, 'Physical', 100);
INSERT INTO Moves VALUES (451,'Comet Punch', 'Normal', 18, 'Physical', 85);
INSERT INTO Moves VALUES (452,'Fury Swipes', 'Normal', 18, 'Physical', 80);
INSERT INTO Moves VALUES (453,'Barrage', 'Normal', 15, 'Physical', 85);
INSERT INTO Moves VALUES (454,'Bind', 'Normal', 15, 'Physical', 85);
INSERT INTO Moves VALUES (455,'Double Slap', 'Normal', 15, 'Physical', 85);
INSERT INTO Moves VALUES (456,'Fury Attack', 'Normal', 15, 'Physical', 85);
INSERT INTO Moves VALUES (457,'Wrap', 'Normal', 15, 'Physical', 90);
INSERT INTO Moves VALUES (458,'Constrict', 'Normal', 10, 'Physical', 100);
INSERT INTO Moves VALUES (459,'Bide', 'Normal', 1, 'Physical', 0);
INSERT INTO Moves VALUES (460,'Crush Grip', 'Normal', 1, 'Physical', 100);
INSERT INTO Moves VALUES (461,'Endeavor', 'Normal', 1, 'Physical', 100);
INSERT INTO Moves VALUES (462,'Flail', 'Normal', 1, 'Physical', 100);
INSERT INTO Moves VALUES (463,'Frustration', 'Normal', 1, 'Physical', 100);
INSERT INTO Moves VALUES (464,'Guillotine', 'Normal', 1, 'Physical', 30);
INSERT INTO Moves VALUES (465,'Horn Drill', 'Normal', 1, 'Physical', 30);
INSERT INTO Moves VALUES (466,'Natural Gift', 'Normal', 1, 'Physical', 100);
INSERT INTO Moves VALUES (467,'Present', 'Normal', 1, 'Physical', 90);
INSERT INTO Moves VALUES (468,'Return', 'Normal', 1, 'Physical', 100);
INSERT INTO Moves VALUES (469,'Sonic Boom', 'Normal', 1, 'Special', 90);
INSERT INTO Moves VALUES (470,'Spit Up', 'Normal', 1, 'Special', 100);
INSERT INTO Moves VALUES (471,'Super Fang', 'Normal', 1, 'Physical', 90);
INSERT INTO Moves VALUES (472,'Trump Card', 'Normal', 1, 'Special', 0);
INSERT INTO Moves VALUES (473,'Wring Out', 'Normal', 1, 'Special', 100);
INSERT INTO Moves VALUES (474 ,'Acupressure', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (475 ,'After You', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (476 ,'Assist', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (477 ,'Attract', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (478 ,'Baton Pass', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (479 ,'Belly Drum', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (480 ,'Bestow', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (481 ,'Block', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (482 ,'Camouflage', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (483 ,'Captivate', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (484 ,'Celebrate', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (485 ,'Confide', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (486 ,'Conversion', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (487 ,'Conversion 2', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (488 ,'Copycat', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (489 ,'Court Change', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (490 ,'Defense Curl', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (491 ,'Disable', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (492 ,'Double Team', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (493 ,'Encore', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (494 ,'Endure', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (495 ,'Entrainment', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (496 ,'Flash', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (497 ,'Focus Energy', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (498 ,'Follow Me', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (499 ,'Foresight', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (500 ,'Glare', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (501 ,'Growl', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (502 ,'Growth', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (503 ,'Happy Hour', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (504 ,'Harden', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (505 ,'Heal Bell', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (506 ,'Helping Hand', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (507 ,'Hold Hands', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (508 ,'Howl', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (509 ,'Laser Focus', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (510 ,'Leer', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (511 ,'Lock-On', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (512 ,'Lovely Kiss', 'Normal', NULL, 'Status', 75);
INSERT INTO Moves VALUES (513 ,'Lucky Chant', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (514 ,'Me First', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (515 ,'Mean Look', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (516 ,'Metronome', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (517 ,'Milk Drink', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (518 ,'Mimic', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (519 ,'Mind Reader', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (520 ,'Minimize', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (521 ,'Morning Sun', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (522 ,'Nature Power', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (523 ,'Noble Roar', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (524 ,'Odor Sleuth', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (525 ,'Pain Split', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (526 ,'Perish Song', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (527 ,'Play Nice', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (528 ,'Protect', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (529 ,'Psych Up', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (530 ,'Recover', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (531 ,'Recycle', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (532 ,'Reflect Type', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (533 ,'Refresh', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (534 ,'Roar', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (535 ,'Safeguard', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (536 ,'Scary Face', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (537 ,'Screech', 'Normal', NULL, 'Status', 85);
INSERT INTO Moves VALUES (538 ,'Sharpen', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (539 ,'Shell Smash', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (540 ,'Simple Beam', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (541 ,'Sing', 'Normal', NULL, 'Status', 55);
INSERT INTO Moves VALUES (542 ,'Sketch', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (543 ,'Slack Off', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (544 ,'Sleep Talk', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (545 ,'Smokescreen', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (546 ,'Soft-Boiled', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (547 ,'Splash', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (548 ,'Spotlight', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (549 ,'Stockpile', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (550 ,'Stuff Cheeks', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (551 ,'Substitute', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (552 ,'Supersonic', 'Normal', NULL, 'Status', 55);
INSERT INTO Moves VALUES (553 ,'Swagger', 'Normal', NULL, 'Status', 85);
INSERT INTO Moves VALUES (554 ,'Swallow', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (555 ,'Sweet Scent', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (556 ,'Swords Dance', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (557 ,'Tail Whip', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (558 ,'Tearful Look', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (559 ,'Teatime', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (560 ,'Teeter Dance', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (561 ,'Tickle', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (562 ,'Transform', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (563 ,'Whirlwind', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (564 ,'Wish', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (565 ,'Work Up', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (566 ,'Yawn', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (567,'Belch', 'Poison', 120, 'Special', 90);
INSERT INTO Moves VALUES (568,'Gunk Shot', 'Poison', 120, 'Physical', 80);
INSERT INTO Moves VALUES (569,'Sludge Wave', 'Poison', 95, 'Special', 100);
INSERT INTO Moves VALUES (570,'Shell Side Arm', 'Poison', 90, 'Special', 100);
INSERT INTO Moves VALUES (571,'Sludge Bomb', 'Poison', 90, 'Special', 100);
INSERT INTO Moves VALUES (572,'Poison Jab', 'Poison', 80, 'Physical', 100);
INSERT INTO Moves VALUES (573,'Cross Poison', 'Poison', 70, 'Physical', 100);
INSERT INTO Moves VALUES (574,'Sludge', 'Poison', 65, 'Special', 100);
INSERT INTO Moves VALUES (575,'Venoshock', 'Poison', 65, 'Special', 100);
INSERT INTO Moves VALUES (576,'Clear Smog', 'Poison', 50, 'Special', 0);
INSERT INTO Moves VALUES (577,'Poison Fang', 'Poison', 50, 'Physical', 100);
INSERT INTO Moves VALUES (578,'Poison Tail', 'Poison', 50, 'Physical', 100);
INSERT INTO Moves VALUES (579,'Acid', 'Poison', 40, 'Special', 100);
INSERT INTO Moves VALUES (580,'Acid Spray', 'Poison', 40, 'Special', 100);
INSERT INTO Moves VALUES (581,'Smog', 'Poison', 30, 'Special', 70);
INSERT INTO Moves VALUES (582,'Poison Sting', 'Poison', 15, 'Physical', 100);
INSERT INTO Moves VALUES (583 ,'Acid Armor', 'Poison', NULL, 'Status', 0);
INSERT INTO Moves VALUES (584 ,'Baneful Bunker', 'Poison', NULL, 'Status', 0);
INSERT INTO Moves VALUES (585 ,'Coil', 'Poison', NULL, 'Status', 0);
INSERT INTO Moves VALUES (586 ,'Corrosive Gas', 'Poison', NULL, 'Status', 100);
INSERT INTO Moves VALUES (587 ,'Gastro Acid', 'Poison', NULL, 'Status', 100);
INSERT INTO Moves VALUES (588 ,'Poison Gas', 'Poison', NULL, 'Status', 90);
INSERT INTO Moves VALUES (589 ,'Poison Powder', 'Poison', NULL, 'Status', 75);
INSERT INTO Moves VALUES (590 ,'Purify', 'Poison', NULL, 'Status', 0);
INSERT INTO Moves VALUES (591 ,'Toxic', 'Poison', NULL, 'Status', 90);
INSERT INTO Moves VALUES (592 ,'Toxic Spikes', 'Poison', NULL, 'Status', 0);
INSERT INTO Moves VALUES (593 ,'Toxic Thread', 'Poison', NULL, 'Status', 100);
INSERT INTO Moves VALUES (594 ,'Venom Drench', 'Poison', NULL, 'Status', 100);
INSERT INTO Moves VALUES (595,'Prismatic Laser', 'Psychic', 160, 'Special', 100);
INSERT INTO Moves VALUES (596,'Psycho Boost', 'Psychic', 140, 'Special', 90);
INSERT INTO Moves VALUES (597,'Future Sight', 'Psychic', 120, 'Special', 100);
INSERT INTO Moves VALUES (598,'Synchronoise', 'Psychic', 120, 'Special', 100);
INSERT INTO Moves VALUES (599,'Dream Eater', 'Psychic', 100, 'Special', 100);
INSERT INTO Moves VALUES (600,'Photon Geyser', 'Psychic', 100, 'Special', 100);
INSERT INTO Moves VALUES (601,'Psystrike', 'Psychic', 100, 'Special', 100);
INSERT INTO Moves VALUES (602,'Freezing Glare', 'Psychic', 90, 'Special', 100);
INSERT INTO Moves VALUES (603,'Psychic', 'Psychic', 90, 'Special', 100);
INSERT INTO Moves VALUES (604,'Psychic Fangs', 'Psychic', 85, 'Physical', 100);
INSERT INTO Moves VALUES (605,'Eerie Spell', 'Psychic', 80, 'Special', 100);
INSERT INTO Moves VALUES (606,'Expanding Force', 'Psychic', 80, 'Special', 100);
INSERT INTO Moves VALUES (607,'Extrasensory', 'Psychic', 80, 'Special', 100);
INSERT INTO Moves VALUES (608,'Hyperspace Hole', 'Psychic', 80, 'Special', 0);
INSERT INTO Moves VALUES (609,'Psyshock', 'Psychic', 80, 'Special', 100);
INSERT INTO Moves VALUES (610,'Zen Headbutt', 'Psychic', 80, 'Physical', 90);
INSERT INTO Moves VALUES (611,'Luster Purge', 'Psychic', 70, 'Special', 100);
INSERT INTO Moves VALUES (612,'Mist Ball', 'Psychic', 70, 'Special', 100);
INSERT INTO Moves VALUES (613,'Psycho Cut', 'Psychic', 70, 'Physical', 100);
INSERT INTO Moves VALUES (614,'Psybeam', 'Psychic', 65, 'Special', 100);
INSERT INTO Moves VALUES (615,'Heart Stamp', 'Psychic', 60, 'Physical', 100);
INSERT INTO Moves VALUES (616,'Confusion', 'Psychic', 50, 'Special', 100);
INSERT INTO Moves VALUES (617,'Stored Power', 'Psychic', 20, 'Special', 100);
INSERT INTO Moves VALUES (618,'Mirror Coat', 'Psychic', 1, 'Special', 100);
INSERT INTO Moves VALUES (619,'Psywave', 'Psychic', 1, 'Special', 100);
INSERT INTO Moves VALUES (620 ,'Agility', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (621 ,'Ally Switch', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (622 ,'Amnesia', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (623 ,'Barrier', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (624 ,'Calm Mind', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (625 ,'Cosmic Power', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (626 ,'Gravity', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (627 ,'Guard Split', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (628 ,'Guard Swap', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (629 ,'Heal Block', 'Psychic', NULL, 'Status', 100);
INSERT INTO Moves VALUES (630 ,'Heal Pulse', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (631 ,'Healing Wish', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (632 ,'Heart Swap', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (633 ,'Hypnosis', 'Psychic', NULL, 'Status', 60);
INSERT INTO Moves VALUES (634 ,'Imprison', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (635 ,'Instruct', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (636 ,'Kinesis', 'Psychic', NULL, 'Status', 80);
INSERT INTO Moves VALUES (637 ,'Light Screen', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (638 ,'Lunar Dance', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (639 ,'Magic Coat', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (640 ,'Magic Powder', 'Psychic', NULL, 'Status', 100);
INSERT INTO Moves VALUES (641 ,'Magic Room', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (642 ,'Meditate', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (643 ,'Miracle Eye', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (644 ,'Power Split', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (645 ,'Power Swap', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (646 ,'Power Trick', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (647 ,'Psychic Terrain', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (648 ,'Psycho Shift', 'Psychic', NULL, 'Status', 100);
INSERT INTO Moves VALUES (649 ,'Reflect', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (650 ,'Rest', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (651 ,'Role Play', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (652 ,'Skill Swap', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (653 ,'Speed Swap', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (654 ,'Telekinesis', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (655 ,'Teleport', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (656 ,'Trick', 'Psychic', NULL, 'Status', 100);
INSERT INTO Moves VALUES (657 ,'Trick Room', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (658 ,'Wonder Room', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (659,'Head Smash', 'Rock', 150, 'Physical', 80);
INSERT INTO Moves VALUES (660,'Rock Wrecker', 'Rock', 150, 'Physical', 90);
INSERT INTO Moves VALUES (661,'Meteor Beam', 'Rock', 120, 'Special', 90);
INSERT INTO Moves VALUES (662,'Diamond Storm', 'Rock', 100, 'Physical', 95);
INSERT INTO Moves VALUES (663,'Stone Edge', 'Rock', 100, 'Physical', 80);
INSERT INTO Moves VALUES (664,'Power Gem', 'Rock', 80, 'Special', 100);
INSERT INTO Moves VALUES (665,'Rock Slide', 'Rock', 75, 'Physical', 90);
INSERT INTO Moves VALUES (666,'Ancient Power', 'Rock', 60, 'Special', 100);
INSERT INTO Moves VALUES (667,'Rock Tomb', 'Rock', 60, 'Physical', 95);
INSERT INTO Moves VALUES (668,'Rock Throw', 'Rock', 50, 'Physical', 90);
INSERT INTO Moves VALUES (669,'Smack Down', 'Rock', 50, 'Physical', 100);
INSERT INTO Moves VALUES (670,'Accelerock', 'Rock', 40, 'Physical', 100);
INSERT INTO Moves VALUES (671,'Rollout', 'Rock', 30, 'Physical', 90);
INSERT INTO Moves VALUES (672,'Rock Blast', 'Rock', 25, 'Physical', 90);
INSERT INTO Moves VALUES (673 ,'Rock Polish', 'Rock', NULL, 'Status', 0);
INSERT INTO Moves VALUES (674 ,'Sandstorm', 'Rock', NULL, 'Status', 0);
INSERT INTO Moves VALUES (675 ,'Stealth Rock', 'Rock', NULL, 'Status', 0);
INSERT INTO Moves VALUES (676 ,'Tar Shot', 'Rock', NULL, 'Status', 100);
INSERT INTO Moves VALUES (677 ,'Wide Guard', 'Rock', NULL, 'Status', 0);
INSERT INTO Moves VALUES (678,'Doom Desire', 'Steel', 140, 'Special', 100);
INSERT INTO Moves VALUES (679,'Steel Beam', 'Steel', 140, 'Special', 95);
INSERT INTO Moves VALUES (680,'Steel Roller', 'Steel', 130, 'Physical', 100);
INSERT INTO Moves VALUES (681,'Behemoth Bash', 'Steel', 100, 'Physical', 100);
INSERT INTO Moves VALUES (682,'Behemoth Blade', 'Steel', 100, 'Physical', 100);
INSERT INTO Moves VALUES (683,'Iron Tail', 'Steel', 100, 'Physical', 75);
INSERT INTO Moves VALUES (684,'Sunsteel Strike', 'Steel', 100, 'Physical', 100);
INSERT INTO Moves VALUES (685,'Meteor Mash', 'Steel', 90, 'Physical', 90);
INSERT INTO Moves VALUES (686,'Anchor Shot', 'Steel', 80, 'Physical', 100);
INSERT INTO Moves VALUES (687,'Flash Cannon', 'Steel', 80, 'Special', 100);
INSERT INTO Moves VALUES (688,'Iron Head', 'Steel', 80, 'Physical', 100);
INSERT INTO Moves VALUES (689,'Smart Strike', 'Steel', 70, 'Physical', 0);
INSERT INTO Moves VALUES (690,'Steel Wing', 'Steel', 70, 'Physical', 90);
INSERT INTO Moves VALUES (691,'Double Iron Bash', 'Steel', 60, 'Physical', 100);
INSERT INTO Moves VALUES (692,'Mirror Shot', 'Steel', 65, 'Special', 85);
INSERT INTO Moves VALUES (693,'Magnet Bomb', 'Steel', 60, 'Physical', 0);
INSERT INTO Moves VALUES (694,'Gear Grind', 'Steel', 50, 'Physical', 85);
INSERT INTO Moves VALUES (695,'Metal Claw', 'Steel', 50, 'Physical', 95);
INSERT INTO Moves VALUES (696,'Bullet Punch', 'Steel', 40, 'Physical', 100);
INSERT INTO Moves VALUES (697,'Gyro Ball', 'Steel', 1, 'Physical', 100);
INSERT INTO Moves VALUES (698,'Heavy Slam', 'Steel', 1, 'Physical', 100);
INSERT INTO Moves VALUES (699,'Metal Burst', 'Steel', 1, 'Physical', 100);
INSERT INTO Moves VALUES (700 ,'Autotomize', 'Steel', NULL, 'Status', 0);
INSERT INTO Moves VALUES (701 ,'Gear Up', 'Steel', NULL, 'Status', 0);
INSERT INTO Moves VALUES (702 ,'Iron Defense', 'Steel', NULL, 'Status', 0);
INSERT INTO Moves VALUES (703 ,'Kings Shield', 'Steel', NULL, 'Status', 0);
INSERT INTO Moves VALUES (704 ,'Metal Sound', 'Steel', NULL, 'Status', 85);
INSERT INTO Moves VALUES (705 ,'Shift Gear', 'Steel', NULL, 'Status', 0);
INSERT INTO Moves VALUES (706,'Hydro Cannon', 'Water', 150, 'Special', 90);
INSERT INTO Moves VALUES (707,'Water Spout', 'Water', 150, 'Special', 100);
INSERT INTO Moves VALUES (708,'Hydro Pump', 'Water', 110, 'Special', 80);
INSERT INTO Moves VALUES (709,'Origin Pulse', 'Water', 110, 'Special', 85);
INSERT INTO Moves VALUES (710,'Steam Eruption', 'Water', 110, 'Special', 95);
INSERT INTO Moves VALUES (711,'Crabhammer', 'Water', 100, 'Physical', 90);
INSERT INTO Moves VALUES (712,'Aqua Tail', 'Water', 90, 'Physical', 90);
INSERT INTO Moves VALUES (713,'Muddy Water', 'Water', 90, 'Special', 85);
INSERT INTO Moves VALUES (714,'Sparkling Aria', 'Water', 90, 'Special', 100);
INSERT INTO Moves VALUES (715,'Surf', 'Water', 90, 'Special', 100);
INSERT INTO Moves VALUES (716,'Fishious Rend', 'Water', 85, 'Physical', 100);
INSERT INTO Moves VALUES (717,'Liquidation', 'Water', 85, 'Physical', 100);
INSERT INTO Moves VALUES (718,'Dive', 'Water', 80, 'Physical', 100);
INSERT INTO Moves VALUES (719,'Scald', 'Water', 80, 'Special', 100);
INSERT INTO Moves VALUES (720,'Snipe Shot', 'Water', 80, 'Special', 100);
INSERT INTO Moves VALUES (721,'Water Pledge', 'Water', 80, 'Special', 100);
INSERT INTO Moves VALUES (722,'Waterfall', 'Water', 80, 'Physical', 100);
INSERT INTO Moves VALUES (723,'Razor Shell', 'Water', 75, 'Physical', 95);
INSERT INTO Moves VALUES (724,'Brine', 'Water', 65, 'Special', 100);
INSERT INTO Moves VALUES (725,'Bubble Beam', 'Water', 65, 'Special', 100);
INSERT INTO Moves VALUES (726,'Octazooka', 'Water', 65, 'Special', 85);
INSERT INTO Moves VALUES (727,'Flip Turn', 'Water', 60, 'Physical', 100);
INSERT INTO Moves VALUES (728,'Water Pulse', 'Water', 60, 'Special', 100);
INSERT INTO Moves VALUES (729,'Aqua Jet', 'Water', 40, 'Physical', 100);
INSERT INTO Moves VALUES (730,'Bubble', 'Water', 40, 'Special', 100);
INSERT INTO Moves VALUES (731,'Water Gun', 'Water', 40, 'Special', 100);
INSERT INTO Moves VALUES (732,'Clamp', 'Water', 35, 'Physical', 85);
INSERT INTO Moves VALUES (733,'Whirlpool', 'Water', 35, 'Special', 85);
INSERT INTO Moves VALUES (734,'Surging Strikes', 'Water', 25, 'Physical', 100);
INSERT INTO Moves VALUES (735,'Water Shuriken', 'Water', 15, 'Special', 100);
INSERT INTO Moves VALUES (736 ,'Aqua Ring', 'Water', NULL, 'Status', 0);
INSERT INTO Moves VALUES (737 ,'Life Dew', 'Water', NULL, 'Status', 0);
INSERT INTO Moves VALUES (738 ,'Rain Dance', 'Water', NULL, 'Status', 0);
INSERT INTO Moves VALUES (739 ,'Soak', 'Water', NULL, 'Status', 100);
INSERT INTO Moves VALUES (740 ,'Water Sport', 'Water', NULL, 'Status', 0);
INSERT INTO Moves VALUES (741 ,'Withdraw', 'Water', NULL, 'Status', 0);
INSERT INTO Moves VALUES (742,'Dire Claw', 'Poison', 80, 'Physical', 100);
INSERT INTO Moves VALUES (743,'Springtide Storm', 'Fairy', 100, 'Special', 80);
INSERT INTO Moves VALUES (744,'Raging Fury', 'Fire', 120, 'Physical', 100);
INSERT INTO Moves VALUES (745,'Wave Crash', 'Water', 120, 'Physical', 100);
INSERT INTO Moves VALUES (746,'Chloroblast', 'Grass', 150, 'Special', 95);
INSERT INTO Moves VALUES (747,'Mountain Gale', 'Ice', 120, 'Physical', 95);
INSERT INTO Moves VALUES (748,'Headlong Rush', 'Ground', 120, 'Physical', 100);
INSERT INTO Moves VALUES (749,'Barb Barrage', 'Poison', 75, 'Physical', 100);
INSERT INTO Moves VALUES (750,'Esper Wing', 'Psychic', 80, 'Special', 100);
INSERT INTO Moves VALUES (751,'Bitter Malice', 'Ghost', 75, 'Special', 100);
INSERT INTO Moves VALUES (752,'Triple Arrows', 'Fighting', 90, 'Physical', 100);
INSERT INTO Moves VALUES (753,'Bleakwind Storm', 'Flying', 100, 'Special', 80);
INSERT INTO Moves VALUES (754,'Wildbolt Storm', 'Electric', 100, 'Special', 80);
INSERT INTO Moves VALUES (755,'Sandsear Storm', 'Ground', 100, 'Special', 80);
INSERT INTO Moves VALUES (756 ,'Lunar Blessing', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (757,'Psyshield Bash', 'Psychic', 85, 'Physical', 100);
INSERT INTO Moves VALUES (758 ,'Power Shift', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (759,'Stone Axe', 'Rock', 65, 'Physical', 90);
INSERT INTO Moves VALUES (760,'Mystical Power', 'Psychic', 85, 'Special', 100);
INSERT INTO Moves VALUES (761 ,'Victory Dance', 'Fighting', NULL, 'Status', 0);
INSERT INTO Moves VALUES (762 ,'Shelter', 'Steel', NULL, 'Status', 0);
INSERT INTO Moves VALUES (763,'Infernal Parade', 'Ghost', 60, 'Special', 100);
INSERT INTO Moves VALUES (764,'Ceaseless Edge', 'Dark', 65, 'Physical', 90);
INSERT INTO Moves VALUES (765 ,'Take Heart', 'Psychic', NULL, 'Status', 0);
INSERT INTO Moves VALUES (766,'Aqua Cutter', 'Water', 70, 'Physical', 100);
INSERT INTO Moves VALUES (767,'Aqua Step', 'Water', 80, 'Physical', 100);
INSERT INTO Moves VALUES (768,'Armor Cannon', 'Fire', 120, 'Special', 100);
INSERT INTO Moves VALUES (769,'Axe Kick', 'Fighting', 120, 'Physical', 90);
INSERT INTO Moves VALUES (770,'Bitter Blade', 'Fire', 90, 'Physical', 100);
INSERT INTO Moves VALUES (771,'Blazing Torque', 'Fire', 80, 'Physical', 100);
INSERT INTO Moves VALUES (772,'Chilling Water', 'Water', 50, 'Special', 100);
INSERT INTO Moves VALUES (773 ,'Chilly Reception', 'Ice', NULL, 'Status', 0);
INSERT INTO Moves VALUES (774,'Collision Course', 'Fighting', 100, 'Physical', 100);
INSERT INTO Moves VALUES (775,'Combat Torque', 'Fighting', 100, 'Physical', 100);
INSERT INTO Moves VALUES (776,'Comeuppance', 'Dark', 1, 'Physical', 100);
INSERT INTO Moves VALUES (777 ,'Doodle', 'Normal', NULL, 'Status', 100);
INSERT INTO Moves VALUES (778,'Double Shock', 'Electric', 120, 'Physical', 100);
INSERT INTO Moves VALUES (779,'Electro Drift', 'Electric', 100, 'Special', 100);
INSERT INTO Moves VALUES (780 ,'Fillet Away', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (781,'Flower Trick', 'Grass', 70, 'Physical', 0);
INSERT INTO Moves VALUES (782,'Gigaton Hammer', 'Steel', 160, 'Physical', 100);
INSERT INTO Moves VALUES (783,'Glaive Rush', 'Dragon', 120, 'Physical', 100);
INSERT INTO Moves VALUES (784,'Hyper Drill', 'Normal', 100, 'Physical', 100);
INSERT INTO Moves VALUES (785,'Ice Spinner', 'Ice', 80, 'Physical', 100);
INSERT INTO Moves VALUES (786,'Jet Punch', 'Water', 60, 'Physical', 100);
INSERT INTO Moves VALUES (787,'Kowtow Cleave', 'Dark', 85, 'Physical', 0);
INSERT INTO Moves VALUES (788,'Last Respects', 'Ghost', 50, 'Physical', 100);
INSERT INTO Moves VALUES (789,'Lumina Crash', 'Psychic', 80, 'Special', 100);
INSERT INTO Moves VALUES (790,'Magical Torque', 'Fairy', 100, 'Physical', 100);
INSERT INTO Moves VALUES (791,'Make It Rain', 'Steel', 120, 'Special', 100);
INSERT INTO Moves VALUES (792,'Mortal Spin', 'Poison', 30, 'Physical', 100);
INSERT INTO Moves VALUES (793,'Noxious Torque', 'Poison', 100, 'Physical', 100);
INSERT INTO Moves VALUES (794,'Order Up', 'Dragon', 80, 'Physical', 100);
INSERT INTO Moves VALUES (795,'Population Bomb', 'Normal', 20, 'Physical', 90);
INSERT INTO Moves VALUES (796,'Pounce', 'Bug', 50, 'Physical', 100);
INSERT INTO Moves VALUES (797,'Rage Fist', 'Ghost', 50, 'Physical', 100);
INSERT INTO Moves VALUES (798,'Raging Bull', 'Normal', 90, 'Physical', 100);
INSERT INTO Moves VALUES (799 ,'Revival Blessing', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (800,'Ruination', 'Dark', 1, 'Special', 90);
INSERT INTO Moves VALUES (801,'Salt Cure', 'Rock', 40, 'Physical', 100);
INSERT INTO Moves VALUES (802 ,'Shed Tail', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (803 ,'Silk Trap', 'Bug', NULL, 'Status', 0);
INSERT INTO Moves VALUES (804 ,'Snowscape', 'Ice', NULL, 'Status', 0);
INSERT INTO Moves VALUES (805 ,'Spicy Extract', 'Grass', NULL, 'Status', 0);
INSERT INTO Moves VALUES (806,'Spin Out', 'Steel', 100, 'Physical', 100);
INSERT INTO Moves VALUES (807,'Tera Blast', 'Normal', 80, 'Special', 100);
INSERT INTO Moves VALUES (808 ,'Tidy Up', 'Normal', NULL, 'Status', 0);
INSERT INTO Moves VALUES (809,'Torch Song', 'Fire', 80, 'Special', 100);
INSERT INTO Moves VALUES (810,'Trailblaze', 'Grass', 50, 'Physical', 100);
INSERT INTO Moves VALUES (811,'Triple Dive', 'Water', 30, 'Physical', 95);
INSERT INTO Moves VALUES (812,'Twin Beam', 'Psychic', 40, 'Special', 100);
INSERT INTO Moves VALUES (813,'Wicked Torque', 'Dark', 80, 'Physical', 100);
INSERT INTO Moves VALUES (814,'Hydro Steam', 'Water', 80, 'Special', 100);
INSERT INTO Moves VALUES (815,'Psyblade', 'Psychic', 80, 'Physical', 100);